"""MCP sampling — the server asking the client's model.

The direction matters and is easy to get backwards: sampling does not let this server
run a model, and it is not a way to keep the client's model from running. It is the
reverse. The value is that pgops ships no API key and pays no inference bill — it
borrows whatever model the user already has.

The load-bearing safety claim, tested below: **sampled output is never executed.** The
model proposes a target *schema*; the SQL is still generated by the deterministic
differ, annotated by the same lock analysis, and gated by the same confirmation flow.
"""

from __future__ import annotations

import json
from typing import Any

import pytest

from pgops.errors import ErrorCode, PgopsError
from pgops.sampling import parse_json_object, sample_json, sample_text
from pgops.tools.migrations import migration_describe


class FakeSampler:
    """Stands in for a client's model. Records what it was asked."""

    def __init__(self, reply: str) -> None:
        self.reply = reply
        self.prompts: list[str] = []
        self.system_prompts: list[str] = []

    async def sample(self, messages: str, **kwargs: Any) -> Any:
        self.prompts.append(messages)
        self.system_prompts.append(kwargs.get("system_prompt", ""))
        return type("R", (), {"text": self.reply})()


class RefusingSampler:
    """A client without sampling support. FastMCP raises rather than returning None."""

    async def sample(self, *args: Any, **kwargs: Any) -> Any:
        raise RuntimeError("client does not support sampling")


# --- parsing model output -------------------------------------------------------------


def test_plain_json_is_parsed() -> None:
    assert parse_json_object('{"tables": {}}') == {"tables": {}}


def test_fenced_json_is_parsed() -> None:
    """Models wrap JSON in a code fence constantly; treating that as a parse failure
    would make the feature flaky for a reason unrelated to the answer."""
    assert parse_json_object('```json\n{"tables": {"a": {}}}\n```') == {"tables": {"a": {}}}


def test_json_preceded_by_prose_is_parsed() -> None:
    text = 'Sure! Here is the target:\n\n{"tables": {"orders": {}}}\n\nLet me know.'
    assert parse_json_object(text) == {"tables": {"orders": {}}}


def test_prose_without_json_returns_none() -> None:
    """A model answering in prose is a normal occurrence, not an exception to raise —
    the caller has a far more useful message than a JSONDecodeError."""
    assert parse_json_object("I am not sure what you want.") is None


def test_json_array_is_rejected() -> None:
    assert parse_json_object("[1, 2, 3]") is None


# --- helpers degrade rather than raise ------------------------------------------------


async def test_sampling_without_a_context_returns_none() -> None:
    assert await sample_text(None, "p", "s") is None
    assert await sample_json(None, "p", "s") is None


async def test_client_without_sampling_returns_none() -> None:
    """Sampling is optional in MCP. Losing it must degrade a feature, never break a
    tool that also does deterministic work."""
    assert await sample_text(RefusingSampler(), "p", "s") is None


async def test_sampled_text_is_returned_with_the_system_role() -> None:
    sampler = FakeSampler("the plan does a seq scan")
    assert await sample_text(sampler, "why slow?", "you explain plans") == (
        "the plan does a seq scan"
    )
    assert sampler.system_prompts == ["you explain plans"]


# --- migration.describe ---------------------------------------------------------------


async def test_describe_turns_english_into_a_real_plan(
    conn_manager: object, config: object
) -> None:
    """The whole point: a sentence becomes a plan with lock analysis, not raw SQL from
    a model."""
    target = {
        "tables": {
            "items": {
                "columns": {
                    "id": {"type": "integer"},
                    "name": {"type": "text", "nullable": False},
                    "note": {"type": "text"},
                }
            }
        }
    }
    sampler = FakeSampler(json.dumps(target))
    result = await migration_describe(
        conn_manager,  # type: ignore[arg-type]
        config,  # type: ignore[arg-type]
        "add a nullable note column to items",
        ctx=sampler,
    )

    assert result["interpreted_target"] == target
    assert [s["sql"] for s in result["steps"]] == ['ALTER TABLE "items" ADD COLUMN "note" text']
    # The deterministic pipeline still ran: this is not a passthrough of model output.
    assert result["steps"][0]["lock_impact"]["risk"] == "low"
    assert result["dry_run_ok"] is True
    assert result["checksum"]


async def test_describe_passes_the_live_schema_to_the_model(
    conn_manager: object, config: object
) -> None:
    """The target describes the desired *final state*, so the model cannot write one
    without seeing the columns that already exist."""
    sampler = FakeSampler('{"tables": {"items": {"columns": {"id": {"type": "integer"}}}}}')
    await migration_describe(
        conn_manager,  # type: ignore[arg-type]
        config,  # type: ignore[arg-type]
        "leave it alone",
        ctx=sampler,
    )
    assert "items" in sampler.prompts[0]
    assert "leave it alone" in sampler.prompts[0]


async def test_describe_without_sampling_support_points_at_migration_plan(
    conn_manager: object, config: object
) -> None:
    with pytest.raises(PgopsError) as exc_info:
        await migration_describe(
            conn_manager,  # type: ignore[arg-type]
            config,  # type: ignore[arg-type]
            "add a column",
            ctx=RefusingSampler(),
        )
    assert exc_info.value.code is ErrorCode.SAMPLING_UNAVAILABLE
    assert "migration.plan" in (exc_info.value.hint or "")


async def test_describe_relays_a_model_refusal_instead_of_guessing(
    conn_manager: object, config: object
) -> None:
    """The system prompt tells the model to say it is unsure rather than invent an
    interpretation. Planning a migration from a guess is the failure worth avoiding."""
    sampler = FakeSampler('{"error": "which table should the column go on?"}')
    with pytest.raises(PgopsError) as exc_info:
        await migration_describe(
            conn_manager,  # type: ignore[arg-type]
            config,  # type: ignore[arg-type]
            "add a column",
            ctx=sampler,
        )
    assert exc_info.value.code is ErrorCode.INVALID_ARGUMENT
    assert "which table" in exc_info.value.message


async def test_model_output_still_goes_through_target_validation(
    conn_manager: object, config: object
) -> None:
    """A hallucinated target is rejected by the same validator a hand-written one hits.
    The model's output is untrusted input, no different from a user's."""
    sampler = FakeSampler('{"tables": {"items": {"triggers": ["do_something"]}}}')
    with pytest.raises(PgopsError) as exc_info:
        await migration_describe(
            conn_manager,  # type: ignore[arg-type]
            config,  # type: ignore[arg-type]
            "add a trigger",
            ctx=sampler,
        )
    assert exc_info.value.code is ErrorCode.INVALID_ARGUMENT


async def test_describe_cannot_smuggle_sql_past_the_planner(
    conn_manager: object, config: object
) -> None:
    """The strongest version of the claim: even if the model emits SQL, there is no path
    from its output to execution — the target format has nowhere to put it."""
    sampler = FakeSampler('{"tables": {}, "sql": "DROP TABLE items"}')
    with pytest.raises(PgopsError):
        await migration_describe(
            conn_manager,  # type: ignore[arg-type]
            config,  # type: ignore[arg-type]
            "drop items",
            ctx=sampler,
        )
    async with conn_manager.acquire_readonly() as conn:  # type: ignore[attr-defined]
        assert await conn.fetchval("SELECT count(*) FROM items") == 250


# --- query.explain summaries ----------------------------------------------------------


async def test_explain_summary_is_opt_in(
    conn_manager: object, config: object, audit: object
) -> None:
    """Sampling spends the user's tokens on the user's model, so it never happens
    because a tool felt like being helpful."""
    from pgops.guardrails import ConfirmationTokenStore
    from pgops.tools.explain import query_explain

    sampler = FakeSampler("It scans every row of items.")
    result = await query_explain(
        conn_manager,  # type: ignore[arg-type]
        config,  # type: ignore[arg-type]
        audit,  # type: ignore[arg-type]
        ConfirmationTokenStore(),
        "SELECT * FROM items",
        ctx=sampler,
    )
    assert "summary" not in result.to_dict()
    assert sampler.prompts == []


async def test_explain_summary_supplements_the_verdicts_rather_than_replacing_them(
    conn_manager: object, config: object, audit: object
) -> None:
    """A model's prose is an addition to the evidence. The plan and the deterministic
    verdicts are returned either way — a client without sampling loses nothing else."""
    from pgops.guardrails import ConfirmationTokenStore
    from pgops.tools.explain import query_explain

    sampler = FakeSampler("It scans every row of items.")
    payload = (
        await query_explain(
            conn_manager,  # type: ignore[arg-type]
            config,  # type: ignore[arg-type]
            audit,  # type: ignore[arg-type]
            ConfirmationTokenStore(),
            "SELECT * FROM items",
            summarize=True,
            ctx=sampler,
        )
    ).to_dict()
    assert payload["summary"] == "It scans every row of items."
    assert payload["plan"]
    assert "verdicts" in payload

    degraded = (
        await query_explain(
            conn_manager,  # type: ignore[arg-type]
            config,  # type: ignore[arg-type]
            audit,  # type: ignore[arg-type]
            ConfirmationTokenStore(),
            "SELECT * FROM items",
            summarize=True,
            ctx=RefusingSampler(),
        )
    ).to_dict()
    assert "summary" not in degraded
    assert degraded["plan"] == payload["plan"]
